name: "Deploy Prod"

on:
  push:
    branches:
      - main

jobs:
  build_image:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4

  deploy:
    runs-on: [self-hosted]
    name: Continuous Deployment
    needs: [build_image]
    steps:
      - name: Read environment variables
        run: echo "DATABASE_URL is ${{ vars.DATABASE_URL }}"
      - name: Deploy Docker stack using Docker Swarm
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          LINKEDIN_CLIENT_ID: ${{ secrets.LINKEDIN_CLIENT_ID }}
          LINKEDIN_CLIENT_SECRET: ${{ secrets.LINKEDIN_CLIENT_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          docker-compose -f docker-compose.build.yml build --no-cache
          docker stack rm taticca-chat-ia
          docker stack deploy -c docker-compose.deploy.yml taticca-chat-ia